### ISSUE TITLE
[BUG] Blank input crashes SysLib 

### ISSUE THREAD

**Issue by yingx9** [AY2324S1-CS2113T-W11-1/tp#119]
**Tested on 2.0 JAR**

Entering blank input crashes SysLib

![image](https://github.com/AY2324S1-CS2113T-W11-1/tp/assets/84222810/8980b427-063b-4c39-8753-c623508aa6aa)

**Tested on 2.0 JAR**

**Comment by 000verflow** [comment]
Been fixed
