### ISSUE TITLE
[DOCUMENTATION] Add note about id for add command

### ISSUE THREAD

**Issue by yingx9** [AY2324S1-CS2113T-W11-1/tp#121]
**Tested on 2.0 JAR**

id needs to be number only, but there is no note or indication about id format in user guide. 

![image](https://github.com/AY2324S1-CS2113T-W11-1/tp/assets/84222810/19bb04ac-a54e-49ac-a4aa-84df37f6338f)

**Comment by JoanneJo** [comment]
ID is not an input argument in v2.1.
