### ISSUE TITLE
[BUG] id, ISBN can be negative for add command 

### ISSUE THREAD

**Issue by yingx9** [AY2324S1-CS2113T-W11-1/tp#122]
**Tested on 2.0 JAR**

Input:  add /id -999 /t Moby Dick /a Herman Melville /tag B /i -999 /g Adventure, Fiction

**Expected**: Error message about negative id and isbn 

**Actual:** 
![image](https://github.com/AY2324S1-CS2113T-W11-1/tp/assets/84222810/12f1385b-ce06-4215-a1a1-2430b12c8f77)

**Consequences**

delete /id -999 fails because there's a check for negative id. Resource is stuck permanently

![image](https://github.com/AY2324S1-CS2113T-W11-1/tp/assets/84222810/29d898c3-f8a9-4373-a136-f040df6e43b6)

**Solution***: Fix a format for ISBN. Do checks for positive number for add command

**Comment by JoanneJo** [comment]
ID is not an input argument in v2.1. Negative ISBN fixed.
