### ISSUE TITLE
[BUG] find /id not working 

### ISSUE THREAD

**Issue by yingx9** [AY2324S1-CS2113T-W11-1/tp#124]
**Tested on 2.0 JAR**

Steps:

1.  `add /id 123 /t Moby Dick /a Herman Melville /tag B /i 9780763630188 /g Adventure, Fiction`
2.  `find /id 123`

**Expected**: Found resource

**Actual**: No resource found 

![image](https://github.com/AY2324S1-CS2113T-W11-1/tp/assets/84222810/214215b1-b6a0-4677-b1c7-6f48e7ead6c5)

**Comment by 000verflow** [comment]
Resolved in 2.1
