### ISSUE TITLE
[Bug] Storage.txt is not stored in data folder

### ISSUE THREAD

**Issue by bnjm2000** [AY2324S1-CS2113T-W11-1/tp#209]
Storage.txt is not stored in data folder but stored in root folder as a hidden file.
Otherwise, still works (stores and loads fine)
![telegram-cloud-photo-size-1-5084598343790865908-m](https://github.com/AY2324S1-CS2113T-W11-1/tp/assets/142559789/4bf670c8-c464-4db1-8169-51fc2e012d4a)

**Comment by 000verflow** [comment]
Fixed, bug with mkdir function for mac os
